### ISSUE TITLE
Governance transaction details are not shown

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-scan#1]
**Bug Description**
I have noticed that updates to pool parameters are described incompletely on the dashboard.
For example, if Capital Bound is changed from 10% to 5%, if one lookup for the specific transaction, what one can see is that it was Governance transaction and not what was exactly change and to what parameter.

I am not sure whether the behavior is the same for all transactions of a Governance type.

**Steps to Reproduce**
Change pool parameter, lookup transaction on the dashboard.

**Expected Result**
Include what was exactly changed and to what value.

**Actual Result**
Pool parameter update -  Governance transaction.

**Versions**
- Software Version: 1.0.8

**Comment by schwartz-concordium** [comment]
Validated solved https://testnet.ccdscan.io/staking?dcount=1&dentity=transaction&dhash=a68c0c94d347d91fe0996a5d717fa590395f060c57de0748aba9ddba7e0e5fd1
Thanks @mh-concordium
