### ISSUE TITLE
Testing Information : Tokens List

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-scan#13]

**Comment by SRConcordium** [comment]
![Token_Stagenet Account.png](https://images.zenhubusercontent.com/63286c13156bc449dba8314a/b03a7940-437e-45fa-b676-aa7c0ac32b4e)

**Comment by SRConcordium** [comment]
![Transfer Token_Stagenet Account.png](https://images.zenhubusercontent.com/63286c13156bc449dba8314a/d6121049-2360-4cdb-a6c6-f21af79afbb7)

**Comment by SRConcordium** [comment]
![No Token_Account.png](https://images.zenhubusercontent.com/63286c13156bc449dba8314a/e60da092-a48e-450f-a18a-b9b3dc49fe58)

**Comment by SRConcordium** [comment]
![Copy Token.png](https://images.zenhubusercontent.com/63286c13156bc449dba8314a/64aac18b-efc9-4060-8c2c-58c7b3c89507)

**Comment by parv0888** [comment]
> 

Even the transactions on the side bar don't update automatically. The way the frontend is currently built. The account information is fetched at one go and then is not updated. 
![image](https://user-images.githubusercontent.com/1246947/196513929-3f7b2527-1d61-45a0-831a-93699e33f6a2.png)

**Comment by parv0888** [comment]
> @parv0888, couple of more observations -
> 
> 1. If there is no token data, the header tab should be removed (screenshot, No Token_Account)
> 2. The "copy" option (Screenshot, Copy Token) for any token ID, copies a local location, I am not sure who needs to provide a working URL for more token info.?

1. Done
2. Copy was meant to copy the Tokens Metadata Url. It might have been the case that the token you were testing for did not have a metadata url, It was fixed by now showing the metadata url copy icon when metadata url is not present.

https://github.com/Concordium/concordium-scan/pull/18

**Comment by SRConcordium** [comment]
@parv0888 , above two issues are resolved now. 

but the reloading/refreshing of token is still an issue, any change in token status in an account is reflected only after reloading CCDScan site and then reloading account again. This doesnt seem very nice user experience if user has to reload CCDScan page again.

**Comment by concordium-cl** [comment]
@SRConcordium Please create feature request for remaining refreshing issue and close ticket.

**Comment by SRConcordium** [comment]
https://github.com/Concordium/concordium-scan/issues/31 is created for refresh issue. 
https://github.com/Concordium/concordium-scan/issues/32 is created for pagination improvement.

Closing this ticket.
