### ISSUE TITLE
Search field unusable at ~1400px breakpoint

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-scan#184]
**Bug Description**
At a certain scale, the search field in the nav bar is very slim:

<img width="1332" alt="Screenshot 2024-02-07 at 09 37 41" src="https://github.com/Concordium/concordium-scan/assets/828403/32de6f6d-ee83-46d9-bb94-837458ac3bc3">

This makes the search bar, and especially the search result selection very hard to use. The width of the page in the screenshot is 1440px.

It looks like this is mainly an issue due to the version tag which seems to include a checksum locally, but even on ccdscan.io, the search field width could be improved. Probably due to more items being added to the nav bar. I think it would activate the layout for the breakpoint below earlier.

**ccdscan.io**
<img width="1425" alt="Screenshot 2024-02-07 at 09 43 26" src="https://github.com/Concordium/concordium-scan/assets/828403/195c75e6-ce80-4ad1-bc99-11d1c1db6d66">

**Steps to Reproduce**
- Scale website to 1440px width

**Expected Result**
Search field has a width which makes it possible to read the contents

**Actual Result**
Search field is accessible, but the contents are unreadable

**Comment by schwartz-concordium** [comment]
Solved in frontend 1.5.40
