### ISSUE TITLE
Token display does not work when there are many tokens.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-scan#19]
**Task description**

The CCDScan account display does not work when an account owns many tokens. The entire set of tokens is returned to the frontend by the looks of it, and sometimes that leads to "error", sometimes to a frozen frontend.

An example is here https://stagenet.ccdscan.io/accounts?dcount=1&dentity=account&daddress=4ZXndsiRAtHFpKZeKpHS5xDyGrMHy9oYfCKQmf9VmRATx4GTzY

I tried in firefox and after loading for 20s or so I get to the account display. But then no actions work, and the site/tab is using 780MB of memory.

**Comment by concordium-cl** [comment]
Pls verify on stagenet.

**Comment by SRConcordium** [comment]
Fix for this issue was verified as part of https://github.com/Concordium/concordium-scan/issues/13, pagination is implemented if there's lot of tokens to show.

https://github.com/Concordium/concordium-scan/issues/32 is created for pagination improvement.

**Comment by SRConcordium** [comment]
Verified again in Stagenet, https://stagenet.ccdscan.io/?dcount=1&dentity=account&daddress=4sH15AxjthA9DYhCux3aVUtPMemD1oJCL4WFiUXcJKqAeeQ9oc
using account 4sH15AxjthA9DYhCux3aVUtPMemD1oJCL4WFiUXcJKqAeeQ9oc, account is loading ok, pagination is introduced that's showing 10 token on one page.
