### ISSUE TITLE
Amounts in contracts are "double"

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-scan#193]
**Bug Description**

Amounts in contracts, for example the `GetAmount` method of COntract class, or the graphql amount property of the contract Type are modeled as floating point numbers.

This is quite wrong and will lead to problems with precision since CCD amounts are not accurately representable with floats.

**Comment by schwartz-concordium** [comment]
Fixed in PR https://github.com/Concordium/concordium-scan/pull/196/files#
backend 1.8.16 and frontend 1.5.39
