### ISSUE TITLE
[CCDSCAN] Maintanence information window

### ISSUE THREAD

**Issue by bogacyigitbasi** [Concordium/concordium-scan#266]
"Currently we are renovating ccdscan, if your transaction doesnt exist please try to refresh or check it on ccdexplorer.io and get in touch with the team. You can follow the progress in this GitHub repository"

We can put something like below. 

<img src="https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/be031c98-be12-467e-8571-62968dfd304e/bd8a360c-720b-4904-bb6c-e90e93b8c7ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS9iZTAzMWM5OC1iZTEyLTQ2N2UtODU3MS02Mjk2OGRmZDMwNGUvYmQ4YTM2MGMtNzIwYi00OTA0LWJiNmMtZTkwZTkzYjhjN2VkIiwiaWF0IjoxNzI4Mzc0ODMwLCJleHAiOjMzMjk4OTM0ODMwfQ.dwT4g_CQCS9ySBLUI7BU2FqtGF9IHwEydKZxMwPSJmE " alt="image (2).png" width="1012" height="654" />

**Comment by limemloh** [comment]
Done in [https://github.com/Concordium/concordium-scan/pull/289](https://github.com/Concordium/concordium-scan/pull/289)
