### ISSUE TITLE
CCDScan doesn't show what data was registered on chain

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-scan#3]
**Bug Description**
It seems that the only thing CCDScan shows is the transaction type.

![image](https://user-images.githubusercontent.com/98821384/177559312-3c6f270e-3a45-45c4-9d59-56a1bdcdb8d2.png)

**Versions**
- Software Version: 1.1.4-0

**Comment by parv0888** [comment]
raised PR
https://github.com/Concordium/concordium-scan/pull/44
