### ISSUE TITLE
Payday rewards for some of the bakers are not visible

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-scan#35]
**Bug Description**
Payday rewards for bakers 1880 and 1004 are not visible.

**Steps to Reproduce**
Select baker id -> Payday Rewards

**Expected Result**

![image](https://user-images.githubusercontent.com/98821384/203630749-d33a4b8e-911e-4746-8b35-f80aff7275ec.png)

**Actual Result**
![image](https://user-images.githubusercontent.com/98821384/203630818-0ad56b89-7298-4d99-8509-bbb27e646f07.png)

Note, for some other bakers payday rewards are visible as for example 1 or 5.
**Versions**
- Software Version: Testnet v?
- OS: Windows
- Browser: Chrome

**Comment by parv0888** [comment]
Thanks noted

**Comment by SRConcordium** [comment]
Verifies OK in Testnet CCDScan, https://concordium-testnet-0.web.app/, refer attached screenshots below - 
![image](https://user-images.githubusercontent.com/113599042/208447558-5418585f-d065-4362-86ac-3b0cb6e074c4.png)
![image](https://user-images.githubusercontent.com/113599042/208447653-14089c09-654b-442c-b543-3a200192155e.png)
