### ISSUE TITLE
Transfer is counted twice in the account balance

### ISSUE THREAD

**Issue by Thahara** [Concordium/concordium-scan#5]
**Bug Description**
It seems in some instances a transaction is added twice.
Looking at the "[Account Statement](https://ccdscan.io/?dcount=1&dentity=account&daddress=3AoCqfjPvAUkQRonNTQ9qLeGnhdkrQ6hx7ULcnocX7gDjtX2YX)" the first transaction transfers 15,000 ccd to the account after which the balance is somehow 30,000 ccd. 
<img width="671" alt="image" src="https://user-images.githubusercontent.com/8398864/179942422-d60b0731-7cc1-483a-857c-e29f26b61166.png">

A guess could be that it is because the account and the 15,000 ccd transfer happened in the same [block](https://dashboard.mainnet.concordium.software/chain/62cf999c840cc442597aa9c81622325052f6fbc925335c8a1f9370b0434aaf9d).

**Comment by parv0888** [comment]
Raised PR
https://github.com/Concordium/concordium-scan/pull/41
