### ISSUE TITLE
Account Balance In Genesis Blocks Is not Correct

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-scan#55]
**Bug Description**
During Catchup all Account Balances are 0. 

**Steps to Reproduce**
DROP the database and catchup from Testnet

**Expected Result**
Accounts should have balances equal to their genesis balances

**Actual Result**
All the account balances are zero

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by parv0888** [comment]
Raised PR for this issue
https://github.com/Concordium/concordium-scan/issues/55

**Comment by mh-concordium** [comment]
Calculation for total circulating supply looks correct, I am not sure that I can verify total unlocked CCDs that easy.
There are 2 minor UI issues that I will report.

**Comment by schwartz-concordium** [comment]
@mh-concordium aligned and can close
