### ISSUE TITLE
CIS2 Tokens of Some Accounts not being listed in Account Details Sidebar

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-scan#57]
**Bug Description**
Tokens Listing Bug. 
CIS2 Tokens of some of the account are not being listed on CCD Scan

**Steps to Reproduce**
Check tokens of the Account
https://testnet.ccdscan.io/?dcount=1&dentity=account&daddress=36Z8i8wkGbA2tKmrRgXrofvbTbV68KCfJD1nAVSMYJJBKPo7mw

**Expected Result**
The Interface should list tokens associated with the account

**Actual Result**
No Tokens are being listed

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by mh-concordium** [comment]
Verified.
The list of tokens that appear attached.
Version: version 0.1.0/1.0.1


![image.png](https://images.zenhubusercontent.com/6284893f971a3daf4db6e569/ad08e491-74b2-48ca-b9f6-40279329637e)
