### ISSUE TITLE
Couldn't display account info on CCDScan - Testnet

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-scan#61]
Something went wrong after select to show specific address.

**To reproduce**

1. Paste the address 45Dp7jhi7kmQbapb7LHnDju1y4R3u4YXYusPBcw8cmZw7MgTeU into CCDScan.
2. After found, select to open it.

**Result:**

![image.png](https://images.zenhubusercontent.com/6284893f971a3daf4db6e569/14191a05-3a2c-4f79-933e-1691bf833b0c)

**Expected**
Account info should open as on other accounts.

**Version**
 version 0.1.0/1.0.1

**Comment by SRConcordium** [comment]
Account page is loading OK in Stagenet CCDScan e.g. https://stagenet.ccdscan.io/?dcount=1&dentity=account&daddress=4pUFr8W5fyZ4PfNibSm88UmKgetfi5NrLBAcMhi2zJTpkmpKsv

**Comment by SRConcordium** [comment]
Verified OK in Testnet, the account is loading OK now - 

![image](https://github.com/Concordium/concordium-scan/assets/113599042/8ff32b28-f5de-4232-84c5-20bd00f527a5)
