### ISSUE TITLE
CIS2 token display page

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-scan#65]
The token display now is per-account, e.g., http://ethbridge.testnet.concordium.com/assets/USDC.json

There is a link to token metadata http://ethbridge.testnet.concordium.com/assets/USDC.json as well.

However this link just has to be copied and in any case leads to a JSON object, not very readable.

it would be useful to also have a page that can display just the token. This would ideally include
- token metadata rendered as nicely as possible
- date of creation of the token (i.e., when the first was minted)
- things like total supply, whether it is fungible or not

A more complex thing would then be to add all owners of the token with their balances.

**Comment by schwartz-concordium** [comment]
Described and tracked in issue https://concordium.atlassian.net/browse/CBW-1163
