### ISSUE TITLE
Remove decimals from Backend API when unit is CCD

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-scan#66]
**Bug Description**
Upon calling backend REST API Ex http://localhost:5000/rest/balance-statistics/latest?field=totalamountunlocked&unit=ccd
The values returned have decimal places. When it should have any decimals.

**Steps to Reproduce**
Use postman to call the api
http://localhost:5000/rest/balance-statistics/latest?field=totalamountunlocked&unit=ccd
Or
https://api-ccdscan.mainnet.concordium.software/rest/balance-statistics/latest?field=totalamountunlocked&unit=ccd

**Expected Result**
7514470077

**Actual Result**
7514470077.45811

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
I do not understand why this is the expected result. Can you explain why we don't want decimals?

**Comment by abizjak** [comment]
Last information from the meeting today from @coolmagic is that it is unclear whether we want this change or not. Please provide details @coolmagic once they are clear.

**Comment by coolmagic** [comment]
@abizjak - This is overall explanation of this req.

![image](https://user-images.githubusercontent.com/10180040/236741512-9e874d2a-aa9e-49f5-8280-77d5fe5b8e09.png)

**Comment by SRConcordium** [comment]
Verified OK in Stagenet, on calling API, GET https://stagenet.api.ccdscan.io/rest/balance-statistics/latest?field=totalAmountReleased, result value is without decimal, please refer screenshot below - 

![image](https://github.com/Concordium/concordium-scan/assets/113599042/bc317c01-c53b-4fb0-bcbb-5584d393c785)

**Comment by SRConcordium** [comment]
Verified OK in Mainnet.
