### ISSUE TITLE
Not able to read it completely after clicking '?' on ccdscan.io

### ISSUE THREAD

**Issue by SAK1511** [Concordium/concordium-scan#68]
**Bug Description**

Found out an error after clicking the ‘?’ In front of total CCD in existence, total unlocked ccd and total circulating supply of CCD. We can’t read it completely. 

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by schwartz-concordium** [comment]
Fix in https://github.com/Concordium/concordium-scan/pull/154/files#diff-450b5c6156f4392126611d79d4ab900cf9f9a57efa9ec723770ff7ca71312ed3
