### ISSUE TITLE
Account Statement section show wrong cost for type Fee

### ISSUE THREAD

**Issue by Thahara** [Concordium/concordium-scan#69]
**Bug Description**

The `Account Statement` section shows an incorrect `Amount` for entries with type `Fee`

**Steps to Reproduce**

Go to `Account Statement` for account [4HDCQr](https://ccdscan.io/?dcount=1&dentity=account&daddress=4HDCQrduhiafcKVq6N7EG5Dp8uQ8HJLcPGn8s6nrEJtxHGktrK), for the `Fee` from `Apr 12, 2023, 10:05 AM`, it shows an `Amount` of -2.857428, but the difference in `Balance` is only -1.142572

![image](https://user-images.githubusercontent.com/8398864/231406319-ac49abe5-09aa-4444-8d93-8483678e7cbc.png)

The difference in `Balance` of -1.142572 corresponds to the cost shown on transaction [f9149b](https://ccdscan.io/?dcount=2&dentity=transaction&dhash=f9149bd18ff323bd34da55a73d05c8d752a69416d5863ee4bd3b84ff79168783).

![image](https://user-images.githubusercontent.com/8398864/231407277-d6116aff-471c-4866-b4d5-223cad4a1c83.png)

**Expected Result**

The `Amount` should show -1.142572

**Actual Result**

The `Amount` actually shows -2.857428

**Versions**
Chrome

**Comment by schwartz-concordium** [comment]
Solved in https://github.com/Concordium/concordium-scan/pull/74
