### ISSUE TITLE
CCDSCAN calculates baker removal time wrong

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-scan#7]
**Bug Description**
When deregistering a baker the time is 0 when 3 weeks have gone by, where the baker is actually removed when the payday event passes (10am CEST on mainnet). After that CCDSCAN starts counting the time up agian until the payday actually passes

**Steps to Reproduce**
Deregister a baker sometime except at 10am CEST

**Expected Result**
The baker is removed on the first payday that passes after 3 weeks.

**Actual Result**
CCDSCAN apparently thinks the baker is removed after exactly 3 weeks.

**Comment by parv0888** [comment]
Raised PR
https://github.com/Concordium/concordium-scan/pull/43

**Comment by mh-concordium** [comment]
Tested on 0.1.0/1.0.1. Time is still wrong. Looking at the Stagenet, time of the effective change is before the actual payday while it should be on the payday.

**Comment by mh-concordium** [comment]
Here is an example of baker 4146. Hovering over the '15 days' shows exact time and that time doesn't equal to payday time.

![image](https://user-images.githubusercontent.com/98821384/226432904-f2cd4831-6c8e-47b8-a171-f8d4f7611b9a.png)

**Comment by abizjak** [comment]
I think it is at least very unexpected for users to show the "effective" time in the hover. Nothing really happens at that time, and the baker is not removed.

I think the correct thing to do in the tooltip would be to show when the baker is actually removed, which is the payday after the effective time.
