### ISSUE TITLE
TotalAmountReleased Api Endpoint should work

### ISSUE THREAD

**Issue by parv0888** [Concordium/concordium-scan#75]
**Description**
Coin Gecko Currently uses following api endpoint to get total circulating supply and show on their [web page](https://www.coingecko.com/en/coins/concordium)
https://mainnet.api.ccdscan.io/rest/balance-statistics/latest?field=TotalAmountReleased

The above API endpoint currently responds with a 500 Error. 

**Steps to Reproduce**
a GET request on the described endpoint responds with 500 error.

**Expected Result**
The api endpoint should return `Total Circulating Supply` in Micro CCD by default. ie a number without decimal points. 

**Actual Result**
500 Error

**Comment by SRConcordium** [comment]
Verified OK in Stagenet, https://stagenet.api.ccdscan.io/rest/balance-statistics/latest?field=TotalAmountReleased
![image](https://github.com/Concordium/concordium-scan/assets/113599042/805ac788-0189-443e-aca3-f5bf07e14711)

**Comment by SRConcordium** [comment]
Verified OK in Mainnet.

**Comment by schwartz-concordium** [comment]
Verified OK
