### ISSUE TITLE
CCDScan: Change "Finalization Time"

### ISSUE THREAD

**Issue by sdkonerira** [Concordium/concordium-scan#78]
Update how "Finalization time" is calculated and displayed in CCD scan using the following formula:

- take the block slot time for the last finalized block (i.e., highest finalized block we have in the network)
- take the reported finalization time for this block for all the nodes that have it and take the median or average
- display the difference

**Comment by dg-concordium** [comment]
You should put this in the CCDScan repo, not documentation

**Comment by schwartz-concordium** [comment]
One should look at the last finalized block hash on block info. Say one block has finalized block hash A and then the next different finalized block hash i B. 
Then any block between A and B should have finalization time set to block slot time B - block slot time A.

This PR updates the logic to follow above mentioned
 https://github.com/Concordium/concordium-scan/pull/91

**Comment by schwartz-concordium** [comment]
Done in backend 1.8.12 and frontend 1.5.34
