### ISSUE TITLE
Final height of the chain not visible

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-scan#80]
**Bug Description**
There is no one value that is pointing to the final height of the chain.
One could filter for how many blocks were produced in the last period with max of 1 year.

**Steps to Reproduce**
Open CCDScan on Home page.

**Expected Result**
Total length of the chain should be shown.

**Actual Result**
Total length is not show.

Note:
I think this is useful to know if ones node is up to a final height by comparing its own node height with the total length. I think that it is also good to just show for how long (how many blocks) the chain exists.

**Versions**
- Software Version: version 0.1.2/1.0.2

**Comment by dg-concordium** [comment]
I think you should put this in the CCDScan repo, not documentation.

**Comment by schwartz-concordium** [comment]
@mh-concordium aligned and can close
