### ISSUE TITLE
Stray `</>` character in transaction outcome display

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-scan#84]
**Bug Description**

The description of the error message when contract initialization fails has an odd `</>` character in between the text and module reference.

**Steps to Reproduce**

Go to https://testnet.ccdscan.io/?dcount=1&dentity=transaction&dhash=5d549f79f7a62cb279657b2d4be4d364f7c78d20b3473c581157f2bfc2bd964b

![Screenshot from 2023-06-22 08-48-21](https://github.com/Concordium/concordium-scan/assets/105212/94ae0079-f8df-40b1-9a59-5a81510bfa96)

**Expected Result**

`</>` is not there.

**Actual Result**

See screenshot.

**Versions**
- Software Version: 0.1.2/1.0.2
- OS: Fedora Linux
- Browser: Chromium

**Comment by schwartz-concordium** [comment]
This is the icon we currently use for modules, and it is applied to all module links. I’m not saying we can’t prettify this, but since it isn’t a bug I’m closing the issue.

Feel free to suggest improvements in an improvement if you have ideas for beautifying it :-)

**Comment by schwartz-concordium** [comment]
This is the icon we currently use for modules, and it is applied to all module links. I’m not saying we can’t prettify this, but since it isn’t a bug I’m closing the issue.

Feel free to suggest improvements in an improvement if you have ideas for beautifying it :-)

**Comment by abizjak** [comment]
I don't understand this attitude. This is just not comprehensible UI. The "link" icon is not even clickable.

It looks even worse now than it did.
![image](https://github.com/Concordium/concordium-scan/assets/105212/1f5a6591-2604-4b44-b060-8214870b8dd5)

This icon serves no purpose. Just removing it would make it acceptable.

**Comment by schwartz-concordium** [comment]
You mean the icon itself isn’t clickable and this is a bug?

**Comment by schwartz-concordium** [comment]
I have created a task in Jira to track this improvement for the component. If you notice any missing information, please feel free to add it.
https://concordium.atlassian.net/browse/CBW-1520
